### ISSUE TITLE
decimal integer

### ISSUE THREAD

**Issue by tkan145** [hudson684/IFN660-T5J#1]
not match underscore _ : 0_123 or 0_____123 will give the result of 0 and 123
1_2_3 return 1 ,2 and 3
0123 will give the result of 0 and 123

**Comment by manworldloves** [comment]
Thanks, An. 
Any number starting with a 0 (except for 0) is not a valid decimal integer - it is an octal integer (which we haven't implemented yet).
"1_2_3" returning "1", "2" and "3" is a problem. I think I've got the answer. I'll try and get something out this afternoon.
